export default {
    FONT_SIZE_TITLE: 20,
    FONT_SIZE_LARGE: 16,
    FONT_SIZE_MEDIUM: 14,
    FONT_SIZE_SMALL: 12,

    FONT_WEIGHT_BOLD: 'bold',
    FONT_WEIGHT_SEMI: '600',
    FONT_WEIGHT_LIGHT: '200',

    COLOR_BORDER: '#000000',
    COLOR_KATERINA_BG: '#f3b7b763',
    COLOR_OTHER_BG: '#9393d28c',

    SPACING_XS: 4,
    SPACING_S: 6,
    SPACING_MB: 5,
    PADDING_VERTICAL: 4,
    PADDING_HORIZONTAL: 6,
};